### ISSUE TITLE
Contract compilation fail because of missing env variables. 

### ISSUE THREAD

**Issue by micahaza** [volmexfinance/volmex-core#1]
Cloned and installed node dependencies. Then I tried to compile smart contracts and it failed.

`volmex-core$ npm run compile

> Volmex.Finance@1.0.0 compile
> hardhat compile

Error HH8: There's one or more errors in your config file:

  * Invalid value {"url":"https://eth-mainnet.alchemyapi.io/v2/","accounts":["0x"],"throwOnTransactionFailures":true,"loggingEnabled":true,"gas":5000000,"gasPrice":50000000000,"blockGasLimit":8000000,"timeout":3600000} for HardhatConfig.networks.mainnet - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://eth-kovan.alchemyapi.io/v2/","accounts":["0x"],"throwOnTransactionFailures":true,"loggingEnabled":true} for HardhatConfig.networks.kovan - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://eth-goerli.alchemyapi.io/v2/","accounts":["0x"],"throwOnTransactionFailures":true,"loggingEnabled":true,"gas":5000000,"gasPrice":200000000000,"blockGasLimit":8000000,"timeout":10800000} for HardhatConfig.networks.goerli - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://eth-rinkeby.alchemyapi.io/v2/","accounts":["0x"],"throwOnTransactionFailures":true,"loggingEnabled":true,"gasPrice":10000000000} for HardhatConfig.networks.rinkeby - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://polygon-mumbai.g.alchemy.com/v2/undefined","accounts":["0x"],"throwOnTransactionFailures":true,"loggingEnabled":true} for HardhatConfig.networks.mumbai - Expected a value of type HttpNetworkConfig.
  * Invalid value {"url":"https://polygon-mainnet.g.alchemy.com/v2/undefined","accounts":["0x"],"throwOnTransactionFailures":true,"loggingEnabled":true,"gas":500000,"gasPrice":30000000000,"blockGasLimit":8000000,"timeout":3600000} for HardhatConfig.networks.polygon - Expected a value of type HttpNetworkConfig.
  
To learn more about Hardhat's configuration, please go to https://hardhat.org/config/

For more info go to https://hardhat.org/HH8 or run Hardhat with --show-stack-traces
`
**I'm sure I could fake those env variables to make it successful. Would you please tell me if it is the intended behavior or something which needs a fix?**

**Comment by eth-coder** [comment]
@micahaza `.env` files contain sensitive information, which we do not want to expose. If you want you can set up your credentials and run compile.
